<?php

namespace App\Http\Requests;

use App\Rules\IntegerArray;
use Illuminate\Foundation\Http\FormRequest;

class StorePostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'string|required',
            'body'=> 'string|required',
            'user_ids' => [
                'array',
                'required',
                // We can create a rule through a rule class or through a closure function
                new IntegerArray()
//                function($attribute, $value, $fail){
//                    $integerOnly = collect($value)->every(fn($element) => is_int($element));
//                    if (! $integerOnly){
//                        $fail($attribute . ' can only be integers.');
//                    }
//                }
            ]
        ];
    }

//    public function messages()
//    {
//        return parent::messages(); // TODO: Change the autogenerated stub
//    }

    public function messages()
    {
        return [
            'title.string' => 'Title must be a string',
            'title.required' => 'Title is a required field.',
            'body.required' => 'Body is a required field.',
        ];
    }
}
